/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CeoLoginRouteImport } from './routes/ceo-login'
import { Route as CeoDashboardRouteImport } from './routes/ceo-dashboard'
import { Route as IndexRouteImport } from './routes/index'

const CeoLoginRoute = CeoLoginRouteImport.update({
  id: '/ceo-login',
  path: '/ceo-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoDashboardRoute = CeoDashboardRouteImport.update({
  id: '/ceo-dashboard',
  path: '/ceo-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ceo-dashboard': typeof CeoDashboardRoute
  '/ceo-login': typeof CeoLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ceo-dashboard': typeof CeoDashboardRoute
  '/ceo-login': typeof CeoLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ceo-dashboard': typeof CeoDashboardRoute
  '/ceo-login': typeof CeoLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ceo-dashboard' | '/ceo-login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ceo-dashboard' | '/ceo-login'
  id: '__root__' | '/' | '/ceo-dashboard' | '/ceo-login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CeoDashboardRoute: typeof CeoDashboardRoute
  CeoLoginRoute: typeof CeoLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ceo-login': {
      id: '/ceo-login'
      path: '/ceo-login'
      fullPath: '/ceo-login'
      preLoaderRoute: typeof CeoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo-dashboard': {
      id: '/ceo-dashboard'
      path: '/ceo-dashboard'
      fullPath: '/ceo-dashboard'
      preLoaderRoute: typeof CeoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CeoDashboardRoute: CeoDashboardRoute,
  CeoLoginRoute: CeoLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
